services:
  - type: web
    name: train-times3
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMB_APP_ID
        value: eba925f8
      - key: TMB_APP_KEY
        value: 2464f8dbaaa79d87a408b049a5340f60
      - key: GEMINI_API_KEY
        value: AIzaSyBKp14bKUiDk7KZhdw97QmNWf2pW5k0VUc
